<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Authentification Torzend</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/admin/admin.css') ?>" type="text/css" media="screen, projection" />
<?php echo $this->headScript(); ?>
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>