<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<link href="/css/default/default.css" rel="stylesheet" type="text/css" media="screen" />
<link href="/templates/default/style.css" rel="stylesheet" type="text/css" media="screen" />
<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/js/easySlider1.7.js"></script>
<?php echo $this->headScript(); ?>
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="headerContent">
			<div id="logo"><h1><a href="/">Torzend<span>.fr</span></a></h1></div>
			<?php echo $this->render('layouts/menu.phtml'); ?>
		</div>
	</div>
	<?php if(!is_null($this->layout()->slider)): ?>
		<?php echo $this->layout()->slider; ?>
	<?php endif; ?>
	<div id="page">
		<div id="contentContainer">
			<?php if(!isset($this->noBreadcrumbs)): ?>
			<div id="breadcrumbsContainer"><div id="breadcrumbs"><?php echo $this->navigation()->breadcrumbs()
												->setSeparator('&nbsp;&raquo;&nbsp;')
												->setMinDepth(0); ?>
			</div></div>
			<?php endif; ?>
			<div id="content">
				<?php echo $this->render('layouts/sidebar.phtml'); ?>
				<div id="contentCenter" class="clearfix"><?php echo $this->layout()->content; ?></div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->render('layouts/footer.phtml'); ?>
</body>
</html>