<div id="footer">
	<div id="footerContent">
		<ul>
			<li><a href="<?php echo $this->url(array('action' => 'sitemap', 'controller' => 'index', 'module' => 'default'), false, true); ?>">Plan du site</a></li>
			<li class="separator">|</li>
			<li><a href="<?php echo $this->url(array('action' => 'contact', 'controller' => 'index', 'module' => 'default'), false, true); ?>">Contact</a></li>
		</ul>
		<p>Copyright (c) 2012 torzend.fr All rights reserved.</p>
	</div>
</div>